### PR TITLE
feat(tests/): Added simple test cases for `custom user model`

### PR DESCRIPTION
**Pull request by aniketmaithani**
- updated requirements
- deleted unrequired files from `accounts` app.

### CODE REVIEW

**Comment by aniketmaithani** [comment]
solves #5

**Comment by jonathanchu** [comment]
Looking good so far, nice work @aniketmaithani !

Can you separate the test requirements into a `dev-requirements.txt` so to keep the dependencies separated as to what is necessary and what is only required for running tests.

Also, a quick writeup on how to run these tests in the `README` would be great, too :)

:beers:

**Comment by aniketmaithani** [comment]
@jonathanchu  on it. Updating the PR

**Comment by jonathanchu** [comment]
Awesome, thank you so much! :+1:

**Pull request merged**
